name: Build and Test
on: push                            # This workflow will run on any push to the repository

jobs:
  test:
    runs-on: ubuntu-latest          # Similar to docker, we set up a virtual machine to run our tests

    steps:
      - name: Check out the code    # Each step has a name, some code, and some options
        uses: actions/checkout@v3   # This is a reference to some code to run

      - name: Set up Python 3.11    # This step installs the Python version we want
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies  # This step installs pip, pipenv, and our dependencies
        run: |                      # Note that there's no reference here — just commands to run
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      
      - name: Test with pytest      # Now we run our tests
        run: |
          pipenv run pytest